spring:
  application:
    name: app

  kafka:
    consumer:
      group-id: logstash-group
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#      auto-offset-reset: earliest


