input {
  file {
    path => "/logs/app.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
  }
}

filter {
  grok {
    match => { "message" => "%{TIMESTAMP_ISO8601:timestamp} %{LOGLEVEL:level} %{JAVACLASS:class} - %{GREEDYDATA:log_message}" }
  }
}

output {
  kafka {
    bootstrap_servers => "kafka:9092"
    topic_id => "spring-logs"
  }
  stdout { codec => rubydebug }
}