input {
  file {
    path => "/logs/app.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
  }
}


output {
  kafka {
    bootstrap_servers => "kafka:9092"
    topic_id => "spring-logs"
    codec => plain {
      format => "%{message}"
    }
  }
  stdout { codec => rubydebug }
}