input {
  kafka {
    bootstrap_servers => "kafka:9092"
    topics => ["spring-logs"]
    group_id => "logstash-group"
    auto_offset_reset => "earliest"
  }
}

filter {
  json {
    source => "message"
    skip_on_invalid_json => true
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "spring-boot-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}